### ISSUE TITLE
pie compatibility

### ISSUE THREAD

**Issue by amo13** [Rudloff/openvegemap#66] opened 2019-05-26 16:17 UTC
Does not seem to work on android pie. At least search and locate-me buttons do nothing. 
I am using lineages 16

**Comment by Rudloff** [comment] 2019-05-26 19:25
Hello,
Are you using the Android app or the browser version ?

**Comment by amo13** [comment] 2019-05-26 20:45
I'm using the android app, latest version from f-droid. Didn't know about a browser version yet, but could have guessed it :)

**Comment by Rudloff** [comment] 2019-05-27 20:27
I don't have a Pie device to try to reproduce this on.
Would it be possible to use [Logcat](https://developer.android.com/studio/command-line/logcat) to get an error message ?

**Comment by amo13** [comment] 2019-05-28 11:11
```
05-28 13:07:34.199 W/SurfaceFlinger(251): Attempting to set client state on removed layer: pro.rudloff.openvegemap/pro.rudloff.openvegemap.MainActivity#0
05-28 13:07:34.199 W/SurfaceFlinger(251): Attempting to destroy on removed layer: pro.rudloff.openvegemap/pro.rudloff.openvegemap.MainActivity#0
```
Thanks for looking into this!
I hope this helps... These two messages popped up when trying to tap on settings, locate me, and search in the app menu

**Comment by Rudloff** [comment] 2019-06-02 12:56
I am not sure this warning is related (maybe just a side effect).
Would it be possible to get a complete from when you open the app to when you click on the various buttons?

**Comment by amo13** [comment] 2019-06-10 13:30
[logs-2019-06-10-13-55-58.zip](https://github.com/Rudloff/openvegemap/files/3272201/logs-2019-06-10-13-55-58.zip)

**Comment by Rudloff** [comment] 2019-06-23 13:12
I'm sorry but I don't see anything in these logs that would explain this problem :slightly_frowning_face:

**Comment by Rudloff** [comment] 2019-10-02 20:00
It might be a duplicate of https://github.com/Rudloff/openvegemap-cordova/issues/17.

@amo13 Was your issue that none of the menu items did anything?

**Comment by amo13** [comment] 2019-10-02 22:39
Hey, cool that you're still on it!
OK, this is odd now, because I switched device and I am now using a one plus x, but again with lineageOS 16 (android pie) and now everything works just fine. 
On my moto g3 with the same ROM and setup I remember the menu items did nothing as you say. 
But as I see in the possible duplicate, it has something to do with the webview, so here's an idea: on my g3 I flashed the bromite webview using nanodroid and replaced the system webview of lineageOS. On my current one plus x I did not flash bromite webview and now your app works fine. Maybe there is something about the webview replacement with bromite that is causing this kind of error?

**Comment by Rudloff** [comment] 2019-10-12 11:26
I am not using the Bromite webview, but it definitely seems to be linked to the webview version because it started to happen after a webview update.

Anyway, I am closing in favor of https://github.com/Rudloff/openvegemap-cordova/issues/17.

**Closed by Rudloff** 2019-10-12 11:26 UTC
